import sys

EXIT_QUEUE_PREFIX = "stdl.exit"
DONE_QUEUE_NAME = "stdl.done"

RECORDER_DEFAULT_RESTART_DELAY_SEC = 3
RECORDER_DEFAULT_CHUNK_THRESHOLD = 10

STREAMLINK_RETRY_COUNT = 5
STREAMLINK_BUFFER_SIZE = sys.maxsize
# STREAMLINK_BUFFER_SIZE = 4 * 1024 * 1024
