{
 "title": "RecNode",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values({job=\"recnode-server\"},instance)"
    }
   },
   {
    "name": "platform",
    "label": "Platform",
    "query": {
     "query": "label_values({job=\"recnode-server\"},platform)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HLS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "M3U8 Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(m3u8_request_duration_seconds_bucket{instance=\"$node\",platform=\"$platform\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.50, rate(m3u8_request_duration_seconds_bucket{instance=\"$node\",platform=\"$platform\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.10, rate(m3u8_request_duration_seconds_bucket{instance=\"$node\",platform=\"$platform\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "M3U8 Request Retries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(m3u8_request_retries_total{instance=\"$node\",platform=\"$platform\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Segment Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(segment_request_duration_seconds_bucket{instance=\"$node\",platform=\"$platform\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, rate(segment_request_duration_seconds_bucket{instance=\"$node\",platform=\"$platform\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.10, rate(segment_request_duration_seconds_bucket{instance=\"$node\",platform=\"$platform\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interval Excution Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(interval_duration_seconds_bucket{instance=\"$node\",platform=\"$platform\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.50, rate(interval_duration_seconds_bucket{instance=\"$node\",platform=\"$platform\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.10, rate(interval_duration_seconds_bucket{instance=\"$node\",platform=\"$platform\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Segment Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(segment_request_failures_total{instance=\"$node\",platform=\"$platform\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Segment Request Retries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(segment_request_retries_bucket{instance=\"$node\",platform=\"$platform\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.50, rate(segment_request_retries_bucket{instance=\"$node\",platform=\"$platform\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.10, rate(segment_request_retries_bucket{instance=\"$node\",platform=\"$platform\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Redis Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(redis_request_duration_seconds_bucket{instance=\"$node\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.50, rate(redis_request_duration_seconds_bucket{instance=\"$node\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.10, rate(redis_request_duration_seconds_bucket{instance=\"$node\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(redis_replica_requests_total{instance=\"$node\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(redis_master_requests_total{instance=\"$node\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "S3 Upload Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(object_write_duration_seconds_bucket{instance=\"$node\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, rate(object_write_duration_seconds_bucket{instance=\"$node\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.10, rate(object_write_duration_seconds_bucket{instance=\"$node\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Platform Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(api_request_duration_seconds_bucket{instance=\"$node\",platform=\"$platform\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.50, rate(api_request_duration_seconds_bucket{instance=\"$node\",platform=\"$platform\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.10, rate(api_request_duration_seconds_bucket{instance=\"$node\",platform=\"$platform\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}