apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.global.name }}-{{ .Values.jobSuffix }}
  namespace: {{ .Values.global.namespace }}
spec:
  template:
    spec:
      containers:
        - name: {{ .Values.global.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: CONFIG_PATH
              value: {{ .Values.configMap.mountPath }}/conf.yaml
            - name: OUT_DIR_PATH
              value: {{ .Values.persistence.nfs.mountPath }}
            - name: TMP_DIR_PATH
              value: {{ .Values.persistence.ceph.mountPath }}
            - name: PY_ENV
              value: prod
          volumeMounts:
            - name: nfs
              mountPath: {{ .Values.persistence.nfs.mountPath }}
            - name: ceph
              mountPath: {{ .Values.persistence.ceph.mountPath }}
            - name: conf
              mountPath: {{ .Values.configMap.mountPath }}
              readOnly: true
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: {{ .Values.global.name }}
        - name: ceph
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.ceph.namePrefix }}{{ .Values.jobSuffix }}
        - name: conf
          configMap:
            name: {{ .Values.configMap.namePrefix }}{{ .Values.jobSuffix }}
      restartPolicy: Never
  backoffLimit: 0
