apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.ceph.namePrefix }}{{ .Values.jobSuffix }}
  namespace: {{ .Values.global.namespace }}
spec:
  storageClassName: {{ .Values.persistence.ceph.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.ceph.requests }}
