apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.global.name }}-{{ .Values.jobSuffix }}
  namespace: {{ .Values.global.namespace }}
spec:
  template:
    spec:
      containers:
        # - name: gluetun
        #   image: {{ .Values.gluetun.repository }}:{{ .Values.gluetun.tag }}
        #   securityContext:
        #     capabilities:
        #       add: ["NET_ADMIN"]
        #   env:
        #     - name: VPN_SERVICE_PROVIDER
        #       value: "protonvpn"
        #     - name: OPENVPN_USER
        #       valueFrom:
        #         secretKeyRef:
        #           name: stdl-proton-secret
        #           key: {{ .Values.secret.userKey }}
        #     - name: OPENVPN_PASSWORD
        #       valueFrom:
        #         secretKeyRef:
        #           name: stdl-proton-secret
        #           key: {{ .Values.secret.passwordKey }}
        #     - name: SERVER_COUNTRIES
        #       value: "Korea"
        #     - name: DNS_ADDRESS
        #       value: "8.8.8.8"
        - name: {{ .Values.global.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: CONFIG_PATH
              value: {{ .Values.configMap.mountPath }}/conf.yaml
            - name: OUT_DIR_PATH
              value: {{ .Values.persistence.nfs.mountPath }}
            - name: TMP_DIR_PATH
{{/*              value: {{ .Values.persistence.ceph.mountPath }}*/}}
              value: {{ .Values.persistence.nfs.mountPath }}
            - name: PY_ENV
              value: prod
          volumeMounts:
            - name: nfs
              mountPath: {{ .Values.persistence.nfs.mountPath }}
{{/*            - name: ceph*/}}
{{/*              mountPath: {{ .Values.persistence.ceph.mountPath }}*/}}
            - name: conf
              mountPath: {{ .Values.configMap.mountPath }}
              readOnly: true
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: {{ .Values.global.name }}
{{/*        - name: ceph*/}}
{{/*          persistentVolumeClaim:*/}}
{{/*            claimName: {{ .Values.persistence.ceph.namePrefix }}{{ .Values.jobSuffix }}*/}}
        - name: conf
          configMap:
            name: {{ .Values.configMap.namePrefix }}{{ .Values.jobSuffix }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions: [{ key: memory, operator: In, values: [high] }]
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
      restartPolicy: Never
  backoffLimit: 0
