FROM python:3.13.2-alpine AS rust_builder

WORKDIR /app

# - cargo & rust: Rust 컴파일러
# - gcc, musl-dev, libffi-dev, openssl-dev: Python/Rust 라이브러리 컴파일용 헤더
# - maturin: Rust 프로젝트 빌드 도구
RUN apk add --no-cache \
    git \
    cargo \
    rust \
    gcc \
    musl-dev \
    libffi-dev \
    openssl-dev \
    patchelf \
    && pip install --no-cache-dir maturin

COPY requirements.txt .
COPY Cargo.toml .
COPY pyproject.toml .
COPY src/ src/

RUN pip install --no-cache-dir -r requirements.txt
RUN maturin build --release --strip && \
    pip install target/wheels/*.whl

# --- Final Stage ---
FROM python:3.13.2-alpine

WORKDIR /app

RUN apk add --no-cache git libgcc

COPY --from=rust_builder /usr/local/lib/python3.13/site-packages /usr/local/lib/python3.13/site-packages
COPY --from=rust_builder /usr/local/bin /usr/local/bin
