apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
  namespace: {{ .Values.global.namespace }}
spec:
  service:
    ports:
      - port: {{ .Values.workflow.webhook.port }}
        targetPort: {{ .Values.workflow.webhook.port }}
  webhook:
    recnode:
      port: "{{ .Values.workflow.webhook.port }}"
      endpoint: {{ .Values.workflow.webhook.endpoint }}
      method: {{ .Values.workflow.webhook.method }}
