apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: {{ .Values.global.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: dep
      eventSourceName: webhook
      eventName: {{ .Values.global.name }}
  triggers:
    - template:
        name: recnode-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: {{ .Values.global.name }}-
              spec:
                entrypoint: main
                imagePullSecrets:
                  - name: {{ .Values.image.pullSecret }}
                arguments:
                  parameters:
                    - name: message
                      value: hello
                templates:
                  - name: main
                    inputs:
                      parameters:
                        - name: message
                    container:
                      image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
                      env:
                        - name: PY_ENV
                          value: prod
                        - name: APP_CONFIG
                          value: "{{`{{inputs.parameters.message}}`}}"
                        - name: OUT_DIR_PATH
                          value: {{ .Values.persistence.nfs.mountPath }}
                        - name: TMP_DIR_PATH
                          value: {{ .Values.app.tmpDirPath }}
                        - name: AMQP_HOST
                          value: {{ .Values.app.rabbitmq.host }}
                        - name: AMQP_PORT
                          value: "{{ .Values.app.rabbitmq.port }}"
                        - name: AMQP_USERNAME
                          value: {{ .Values.app.rabbitmq.username }}
                        - name: AMQP_PASSWORD
                          valueFrom:
                            secretKeyRef:
                              name: {{ .Values.app.rabbitmq.secretName }}
                              key: {{ .Values.app.rabbitmq.passwordKey }}
                      volumeMounts:
                        - name: recnode-nfs
                          mountPath: {{ .Values.persistence.nfs.mountPath }}
                      resources:
                        requests:
                          cpu: {{ .Values.resources.requests.cpu }}
                          memory: {{ .Values.resources.requests.memory }}
                    volumes:
                      - name: recnode-nfs
                        persistentVolumeClaim:
                          claimName: {{ .Values.persistence.nfs.pvcName }}
                    affinity:
                      nodeAffinity:
                        requiredDuringSchedulingIgnoredDuringExecution:
                          nodeSelectorTerms:
                            - matchExpressions: [{ key: memory, operator: In, values: [high] }]
                    tolerations:
                      - effect: NoSchedule
                        operator: Exists
                      - key: CriticalAddonsOnly
                        operator: Exists
                      - effect: NoExecute
                        operator: Exists
          parameters:
            - src:
                dependencyName: dep
                dataKey: body
              dest: spec.arguments.parameters.0.value
