---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ .Values.secrets.auth.secretName }}
  namespace: {{ .Values.global.namespace }}
spec:
  vaultAuthGlobalRef:
    name: default-auth
    namespace: vault
    allowDefault: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .Values.secrets.auth.secretName }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: kv-v2
  mount: {{ .Values.vault.mount }}
  path: {{ .Values.secrets.auth.path }}
  version: {{ .Values.vault.version }}
  destination:
    name: {{ .Values.secrets.auth.secretName }}
    create: true
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "telemetry"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "telemetry"
  refreshAfter: {{ .Values.vault.refreshAfter }}
  vaultAuthRef: {{ .Values.secrets.auth.secretName }}
