apiVersion: v1
kind: Service
metadata:
  name: stdl-nodeport-proton
  namespace: media
spec:
  selector:
    controller: eventsource-controller
    eventsource-name: webhook-proton
    owner-name: webhook-proton
  type: NodePort
  ports:
    - port: 12000
      protocol: TCP
      targetPort: 12000
      nodePort: 30721
